name: Deploy

on:
  push:
    tags:
     - v*

env:
  PROJECT_PATH: GeradorChaveNFe/GeradorChaveNFe.csproj
  PUBLISH_PATH: GeradorChaveNFe/bin/Release/net8.0-windows/win-x64/publish

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - run: dotnet restore ${{ env.PROJECT_PATH }} -r win-x64
      - run: dotnet build ${{ env.PROJECT_PATH }} --no-restore -c Release -p:PublishSingleFile=true --self-contained
      - run: dotnet publish ${{ env.PROJECT_PATH }} --no-build -c Release -p:PublishSingleFile=true --self-contained
      - run: rm ${{ env.PUBLISH_PATH }}/*.pdb
      - run: Compress-Archive -Path ${{ env.PUBLISH_PATH }}/*, ./LICENSE -DestinationPath ./GeradorChaveNFe.zip

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ./GeradorChaveNFe.zip


